name: Deployment

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy README.md to docs
        run: |
            sed -i 1s/^/---\\nid:\ main-doc\\nslug:\ \\/\\n---\\n\\nimport\ Image\ from\ \'@theme\\/IdealImage\'\;\\n\\n/ README.md
            sed -i -r s/'<img\ src=\"\.\/docs\/static\/images\/([A-Za-z0-9_-]*.[pngifj]*)\"\ width=\"([0-9.%]*)\">'/'<Image\ img=\{require\(\`\@site\/static\/images\/\1\`)\}\ style={{width:\ \"\2\"}}\/>'/g README.md
            sed -i s/'https\:\/\/coconut-xr.github.io\/natuerlich\/'/'\/category\/how-to-use-natuerlich'/g README.md
            cp README.md docs/docs/README.md

      - name: Install and Build docusaurus docs
        working-directory: docs
        run: |
            npm ci
            npm run build

      - name: Copy README.md and images to public
        run: |
          sed -i 's+./docs/+./+g' README.md
          cp README.md public/README.md
          cp -r images/* public/images
      
      - name: Copy docs to public
        run: |
          cp -r docs/build/* public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
  publish-npm-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install

      - name: Check
        run: npm run check

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-github-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}

      - name: Check
        run: npm run check

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
